### ISSUE TITLE
Erro ao rodar o script - Localização network.py

### ISSUE THREAD

**Issue by lucianasn** [PyMarcus/auto_gpt#1]
Coloquei um print para pegar o conteúdo de link, mas como mostrado abaixo, não tem o caracter "+" e pior, não tem o smell. Estou rodando a mesma base do repositório.

```python
root@19072e3c2a95:/msr2023# python3 main.py
[+]Downloading source codes from github...
Link
https://github.com/apache/syncope/blob/114c412afbfba24ffb4fbc804e5308a823a16a78/client/idrepo/ui/src/main/java/org/apache/syncope/client/ui/commons/ConnIdSpecialName.java/#L35-L37
Traceback (most recent call last):
  File "/msr2023/main.py", line 10, in <module>
    network.start()
  File "/msr2023/network/network.py", line 33, in start
    link, smell = link.split("+")
    ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by PyMarcus** [comment]
Boa noite.Eu vou atualizar o repositorio com as alterações.Nao encontrou o '+' ,por esse motivo.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Luciana Silva ***@***.***>
Sent: Sunday, October 8, 2023 9:39:36 PM
To: PyMarcus/auto_gpt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PyMarcus/auto_gpt] Erro ao rodar o script - Localização network.py (Issue #1)


Coloquei um print para pegar o conteúdo de link, mas como mostrado abaixo, não tem o caracter "+" e pior, não tem o smell. Estou rodando a mesma base do repositório.

***@***.***:/msr2023# python3 main.py
[+]Downloading source codes from github...
Link
https://github.com/apache/syncope/blob/114c412afbfba24ffb4fbc804e5308a823a16a78/client/idrepo/ui/src/main/java/org/apache/syncope/client/ui/commons/ConnIdSpecialName.java/#L35-L37
Traceback (most recent call last):
  File "/msr2023/main.py", line 10, in <module>
    network.start()
  File "/msr2023/network/network.py", line 33, in start
    link, smell = link.split("+")
    ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
